- name: Set Root Passwords
  connection: network_cli
  become: no
  gather_facts: no
  hosts: all
  vars:
   - pass_dir: "passwords"
   - bitwarden_server: "https://bitwarden.beeksfx.com"
   - bitwarden_id: "organization.fb29573f-759b-4955-a9c0-aad40094cf87"
   - bitwarden_secret: "YFoBdz5ihWO352CoTmtdHSiVZQNrgZ"

  tasks:
   - name: Clean Out Password Directory
     file:
       path: "{{ pass_dir }}/build"
       state: absent
     run_once: yes
     delegate_to: localhost

   - name: Create Password Directory
     file: 
        path: "{{ pass_dir }}/build"
        state: directory
     run_once: yes
     delegate_to: localhost

   - name: Generate Password
     set_fact:
       root_pass: "{{ lookup('password','/dev/null chars=ascii_letters,digits')  }}"
     delegate_to: localhost

   - name: Set Root Password
     tags: prod
     junos_config:
       lines:
         - set system root-authentication encrypted-password "{{ root_pass   |  password_hash('sha512') }}"

   - name: copy column headers file
     run_once: yes
     delegate_to: localhost
     template:
      src: templates/bitwarden-host.txt
      dest: "{{ pass_dir }}/build/{{ inventory_hostname }}.csv"

   - name: copy column headers file
     copy:
       src: templates/bitwarden.txt
       dest: "{{ pass_dir}}/build/AAAAAA.txt"
     run_once: yes
     delegate_to: localhost

   - name: assemble inventory report
     assemble:
       src: "{{ pass_dir }}/build"
       dest: "{{ pass_dir }}/report.csv"
     run_once: yes
     delegate_to: localhost

   - name: Cleanup Build Directory
     file:
      path: "{{ pass_dir }}/build"
      state: absent
     run_once: yes
     delegate_to: localhost

   - name: Get Bidwarden Token
     uri:
      url: "{{ bitwarden_server }}/identity/connect/token"
      method: POST
      body_format: "form-urlencoded"
      body: 
       grant_type: client_credentials
       scope: api.organization
       client_id: "{{ bitwarden_id }}"
       client_secret: "{{ bitwarden_secret }}"
     register: token
     run_once: yes
     delegate_to: localhost

   - name: Debug
     debug:
       msg: "{{ token }}"


   

