- name:  Setup SSH Keys for GIT Repo
  gather_facts: no
  hosts: nms50-awx-ld
    
    

  tasks:

    - name: Generate SSH Keys
      delegate_to: localhost
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no        

    - name: Copy to GIT Server 
      authorized_key:
        user: git
        state: present
        key: "{{ lookup('file','~/.ssh/id_rsa') }}"

