- name:  Backup Config
  connection: network_cli
  become: no
  gather_facts: no
  hosts: 
    - management-switch
  roles:
    - Juniper.junos
  vars:
    git_server: "10.78.78.50"
    git_directory: "backups"

  tasks:

   - name: Clone Backup Repo
     run_once: yes
     delegate_to: localhost
     ansible.builtin.git:
       repo: "git@{{ git_server }}:backups.git"
       dest: "{{ git_directory }}"
       accept_hostkey: yes
       update: yes

   - name: Directory Check
     run_once: yes
     delegate_to: localhost
     file:
       path: "{{ git_directory }}"
       state: directory

   - name: LS
     run_once: yes
     delegate_to: localhost
     register: response
     ansible.builtin.shell:
       cmd: pwd

   - name: LS Per Host
     register: response
     ansible.builtin.shell:
       cmd: pwd

   - name: Backup Config
     juniper_junos_config:
       retrieve: "committed"
       dest_dir: "playbooks/{{ git_directory }}"
       timeout: 60

   - name: Git ACP
     run_once: yes
     delegate_to: localhost
     git_acp:
       comment: "Ansible "
       path: backups
       branch: master
       add:
       mode: ssh
       url: "git@{{ git_server }}:backups.git"
       

    
