- name:  Backup Config
  gather_facts: no
  hosts: 
    - management-switch
  roles:
    - Juniper.junos
  vars:
    git_server: "10.78.78.50"
    git_directory: "backups"

  tasks:

   - name: Clone Backup Repo
     run_once: yes
     delegate_to: localhost
     ansible.builtin.git:
       repo: "git@{{ git_server }}:backups.git"
       dest: "{{ git_directory }}"
       accept_hostkey: yes
       update: yes

   - name: Backup Config
     register: response
     juniper_junos_config:
       retrieve: "committed"
       dest_dir: "{{ git_directory }}/backups"
       timeout: 60

