- name: Juniper Management Switches Base Config
  gather_facts: no
  hosts: 
    - management-switch
  remote_user: ansible
  roles:
    - Juniper.junos

  tasks:
   - name: Merge Config
     juniper_junos_config:
      template: "../templates/juniper-switch-mgmt-config.j2"
      load: "merge"
      format: "set"
      provider:
        timeout: 60
     register: response




