- name: Juniper Management Switches Base Config
  gather_facts: no
  hosts: 
    - management-switch
  remote_user: ansible
  roles:
    - Juniper.junos

  tasks:
   - name: Merge Config
     juniper_junos_config:
      template: ../templates/juniper-switch-mgmt-config.j2
      load: "merge"
      format: "set"
      provider:
        timeout: 60
      vars:
        syslog_server: "{{ syslog_server }}"
        ipa_server: "{{ ipa_server }}"
        time_zone: "{{ time_zone }}"
        host_name: "{{ inventory_hostname }}"
        ipa_servers: "{{ ipa_servers }}"
     register: response




