- name:  Backup Config
  connection: network_cli
  become: no
  gather_facts: no
  hosts: 
    - management-switch
    - access-switch
  roles:
    - Juniper.junos
  vars:
    git_server: "10.78.78.50"
    git_directory: "backups"

  tasks:

   - name: Clone Backup Repo
     run_once: yes
     delegate_to: localhost
     ansible.builtin.git:
       repo: "git@{{ git_server }}:backups.git"
       dest: "{{ git_directory }}"
       accept_hostkey: yes
       update: yes

   - name: Backup Config
     ignore_errors: yes
     juniper_junos_config:
       retrieve: "committed"
       dest_dir: "playbooks/{{ git_directory }}"
       timeout: 60

   - name: Git Config user.name
     run_once: yes
     delegate_to: localhost
     ansible.builtin.command: git config user.name AWX
     args:
       chdir: backups

   - name: Git Config user.email
     run_once: yes
     delegate_to: localhost
     ansible.builtin.command: git config user.email awx@beeksfx.com
     args:
       chdir: backups
 
   - name: Git Add
     run_once: yes
     delegate_to: localhost
     ansible.builtin.command: git add .
     args:
       chdir: backups


   - name: Git Commit
     register: commit
     run_once: yes
     delegate_to: localhost
     ignore_errors: yes
     ansible.builtin.command: git commit -a -m ansible
     args:
       chdir: backups

   - name: Git push
     run_once: yes
     delegate_to: localhost
     ansible.builtin.command: git push
     args:
       chdir: backups
     when: commit.changed
    
















