- name:  Copy images and config files to console server
  gather_facts: no
  hosts: console
  vars:
   - file_server: "ipa254-mgmt-ld5"
  collections:
    - opengear.om
 
  tasks:

    - name: .ssh directory
      delegate_to: "{{ file_server }}"
      file:
        path: "~/.ssh"
        state: directory

    - name: Generate SSH Keys
      delegate_to: "{{ file_server }}"
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no        

    - name: Fetch SSH Key
      delegate_to: "{{ file_server }}"
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "./id_rsa.pub"
        flat: yes

    - name: Add authorized key to opengear local ansible user
      connection: httpapi
      opengear.om.om_users:
        config:
          system_authorized_keys:
            - key: "{{ lookup('file','id_rsa.pub') }}"
              username: ansible
              id: users_ssh_authorized_keys-1
        state: deleted

    - name: 
      tags: sync-pull
      copy:
        src: "/ftpstuff/tftpboot/cloud"
        dest: "/var/mnt/storage.sd/tftpboot"
        mode: push
      delegate_to: ipa254-mgmt-ld5



